language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dilicfrancis/react_test -f Dockerfile.dev .

script:
  - docker run -e CI=true dilicfrancis/react_test npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "react_test"
  env: "Reacttest-env"
  bucket_name: "elasticbeanstalk-us-west-1-445288678798"
  bucket_path: "react_test"
  on:
    branch: master
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
