language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dilicfrancis/client-test -f ./client/Dockerfile.dev ./client
  #- docker build -t dilicfrancis/server-test -f ./server/Dockerfile.dev ./server
  #- docker build -t dilicfrancis/worker-test -f ./worker/Dockerfile.dev ./worker

script:
  - docker run -e CI=true dilicfrancis/client-test npm test
  #- docker run dilicfrancis/server-test npm test
  #- docker run -e CI=true dilicfrancis/worker-test npm test

after_success:
  - docker build -t dilicfrancis/multi-client ./client
  - docker build -t dilicfrancis/multi-server ./server
  - docker build -t dilicfrancis/multi-worker ./worker
  - docker build -t dilicfrancis/multi-nginx ./nginx
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take above images and push to docker hub
  - docker push dilicfrancis/multi-client
  - docker push dilicfrancis/multi-server
  - docker push dilicfrancis/multi-worker
  - docker push dilicfrancis/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi_test
  env: Multitest-env
  bucket_name: elasticbeanstalk-us-west-1-445288678798
  bucket_path: "multi-container"
  on:
    branch: master
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
